/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 pipole.gltf 
Author: Squirmy Worm (https://sketchfab.com/squirmyworm064)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/poipole-ddecd139eebf4d88ba7c58e76c90fcad
Title: Poipole
*/

// eslint-disable-next-line no-unused-vars
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/pipole.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.color_10744319} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.color_14093196} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.color_15392511} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.color_2829873} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.color_4920709} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.color_6016255} />
      </group>
    </group>
  )
}

useGLTF.preload('/pipole.gltf')
